language: c
dist: trusty
os: linux

before_install:
  - sudo apt-get install -y libconfig-dev
  - sudo apt-get install -y libsane-dev
  - sudo apt-get install -y libcups2-dev
  - autoreconf -vfi

script:
  - ./configure
  - make
